### ISSUE TITLE
Update the image meta tag.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/poor-mans-styleguide#17]
The current  image metatag results in a 404.

I should replace it with this (or a similar screenshot):

![poor-mans-styleguide](https://user-images.githubusercontent.com/1256329/85327075-50b29480-b49c-11ea-8dc6-4947d060404f.png)

**Comment by Riya-code** [comment]
Can I take it?

**Comment by bryanbraun** [comment]
Yes, be my guest. 🙇‍♂️

**Comment by bryanbraun** [comment]
Yeah, for the image you could use the link to this one in the github issue, which is: https://user-images.githubusercontent.com/1256329/85327075-50b29480-b49c-11ea-8dc6-4947d060404f.png

Or you could create your own that looks like that, by taking a partial screenshot of the homepage of: https://poormansstyleguide.com

**Comment by juliemyoung** [comment]
Bryan, I can do this for Hacktoberfest. I created this image that I could put a PR in to update the broken link. 

<img width="327" alt="poor-mans-style-guide-frontend" src="https://user-images.githubusercontent.com/26744459/137593037-6a5edcaa-5ff0-4fe0-97a7-f9cb83f4c3e4.png">
